# Generated by Django 3.1.13 on 2021-10-11 13:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rich_text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Text')),
                ('question_list', models.ManyToManyField(blank=True, default=None, to='isa_poll.Question')),
                ('topic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='isa_poll.topicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Text')),
                ('rich_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isa_poll.question')),
            ],
        ),
    ]
