# Generated by Django 3.1.13 on 2021-10-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isa_poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Text')),
                ('topic_list', models.ManyToManyField(blank=True, default=None, to='isa_poll.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionerResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128, verbose_name='Text')),
                ('author_name', models.CharField(max_length=128, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_edit', models.DateTimeField(auto_now=True)),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='isa_poll.questioner')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='questioner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='isa_poll.questioner'),
            preserve_default=False,
        ),
    ]
