# Generated by Django 3.1.13 on 2021-10-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isa_poll', '0002_auto_20211013_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionerResults',
            new_name='QuestionerResult',
        ),
    ]
