# Generated by Django 3.1.13 on 2021-10-12 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isa_poll', '0003_auto_20211013_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questioner',
        ),
        migrations.AddField(
            model_name='answer',
            name='questioner_result',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='isa_poll.questionerresult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionerresult',
            name='author_name',
            field=models.CharField(max_length=128, verbose_name='Document author'),
        ),
        migrations.AlterField(
            model_name='questionerresult',
            name='client_name',
            field=models.CharField(max_length=128, verbose_name='Client'),
        ),
    ]
